### ISSUE TITLE
[tf2.7]SASRec模型运行出错

### ISSUE THREAD

**Issue by da-pang-za** [ZiyaoGeng/RecLearn#64]
在TF2.7环境下  运行到evaluate时 predict函数报错，麻烦看一下🙏🏻
Traceback (most recent call last):
  File "/Users/dpz/grad/code/Recommender-System-with-TF2.0/SASRec2/train.py", line 70, in <module>
    hit_rate, ndcg = evaluate_model(model, test, K)
  File "/Users/dpz/grad/code/Recommender-System-with-TF2.0/SASRec2/evaluate.py", line 19, in evaluate_model
    pred_y = - model.predict(test)
  File "/Users/dpz/bin/miniforge3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/dpz/bin/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [32,133] vs. shape[188] = [24,125] [Op:ConcatV2] name: concat

Process finished with exit code 1

**Comment by ZiyaoGeng** [comment]
这涉及了tf2.7在predict部分的更新，如果你切回tf2.6是对的。如果你参考下reclearn分支的代码就对了。
最近没时间改正，有空会更新下，保证兼容性

**Comment by da-pang-za** [comment]
> 这涉及了tf2.7在predict部分的更新，如果你切回tf2.6是对的。如果你参考下reclearn分支的代码就对了。 最近没时间改正，有空会更新下，保证兼容性

谢谢！
